// Altruiso — Investment Inquiry Form Questions

export const questions = [
  // ── Form Page 1: Contact Information ──────────────────
  {
    id: "q_contact",
    type: "contact_group",
    sectionHeader: "Contact Information",
    title: "Contact Information",
    required: true,
    fields: [
      { id: "first_name", label: "First name*", type: "text", required: true },
      { id: "last_name", label: "Last name*", type: "text", required: true },
      { id: "email", label: "Your email address*", type: "email", required: true },
      { id: "social_url", label: "Your LinkedIn or other social profile URL*", type: "url", required: true },
    ],
  },

  // ── Form Page 2: Company Information ──────────────────
  {
    id: "q_company",
    type: "contact_group",
    sectionHeader: "Company Information",
    title: "Company Information",
    required: true,
    fields: [
      { id: "company_name", label: "Company Name*", type: "text", required: true },
      { id: "company_website", label: "Company Website*", type: "url", required: true },
      { id: "business_location", label: "Where is your business based?*", type: "text", required: true },
      { id: "company_description", label: "Briefly describe your business in one or two sentences.*", type: "textarea", required: true },
    ],
  },

  // ── Form Page 3: Business Overview ─────────────────────
  {
    id: "q_problem_customers",
    name: "problem_and_customers",
    type: "long_text",
    sectionHeader: "Business Overview",
    title: "What problem does your business solve, and who are your customers?",
    required: true,
  },
  {
    id: "q_differentiation",
    name: "differentiation",
    type: "long_text",
    sectionHeader: "Business Overview",
    title: "What makes your business different from competitors?",
    required: true,
  },
  {
    id: "q_industry",
    name: "industry",
    type: "dropdown",
    sectionHeader: "Business Overview",
    title: "Which industry best describes your business?",
    required: true,
    options: [
      "Technology",
      "Financial Services",
      "Healthcare",
      "Education",
      "Consumer",
      "Manufacturing",
      "Food & Beverage",
      "Real Estate",
      "Energy",
      "Travel & Hospitality",
      "Professional Services",
      "Other",
    ],
  },
  {
    id: "q_stage",
    name: "business_stage",
    type: "multiple_choice",
    sectionHeader: "Business Overview",
    title: "What stage best describes your business?",
    required: true,
    options: [
      "Revenue-generating",
      "Growth Stage",
      "Mature Business",
      "Acquisition Opportunity",
      "Early Stage (Exceptional Founders)",
    ],
  },

  // ── Form Page 4: Business Performance ──────────────────
  {
    id: "q_employees",
    name: "full_time_employees",
    type: "short_text",
    inputType: "number",
    sectionHeader: "Business Performance",
    title: "How many full-time employees do you have?",
    required: true,
  },
  {
    id: "q_revenue_ltm",
    name: "revenue_ltm_usd",
    type: "short_text",
    inputType: "number",
    prefix: "$",
    sectionHeader: "Business Performance",
    title: "What was your revenue over the last 12 months (USD)?",
    required: true,
  },
  {
    id: "q_profitable",
    name: "is_profitable",
    type: "multiple_choice",
    sectionHeader: "Business Performance",
    title: "Is your business currently profitable?",
    required: true,
    options: ["Yes", "No", "Break-even"],
  },

  // ── Form Page 5: Investment Opportunity ────────────────
  {
    id: "q_capital_seeking",
    name: "capital_seeking",
    type: "short_text",
    inputType: "number",
    prefix: "$",
    sectionHeader: "Investment Opportunity",
    title: "How much capital are you seeking?",
    required: true,
  },
  {
    id: "q_use_of_investment",
    name: "use_of_investment",
    type: "multiple_choice",
    sectionHeader: "Investment Opportunity",
    title: "How do you intend to use the investment?",
    required: true,
    options: [
      "Expansion",
      "Acquisition",
      "Working Capital",
      "Product Development",
      "Hiring",
      "Market Expansion",
      "Other",
    ],
  },
  {
    id: "q_partnership_type",
    name: "partnership_seeking",
    type: "multiple_choice",
    sectionHeader: "Investment Opportunity",
    title: "What type of partnership are you seeking from Altruiso?",
    required: true,
    options: [
      "Capital Only",
      "Strategic Partnership",
      "Operational Guidance",
      "Long-Term Investment Partner",
      "Not Sure",
    ],
  },

  // ── Form Page 6: Supporting Information ────────────────
  {
    id: "q_pitch_deck",
    name: "pitch_deck_url",
    type: "short_text",
    inputType: "url",
    sectionHeader: "Supporting Information",
    title: "Please add link to your Pitch Deck or Investment Memorandum.",
    hint: "(PDF preferred)",
    required: true,
  },
  {
    id: "q_additional_info",
    name: "additional_info",
    type: "long_text",
    sectionHeader: "Supporting Information",
    title: "Is there anything else you'd like us to know?",
    hint: "Optional.",
    required: false,
  },
];
